### ISSUE TITLE
 Can't see scroll bar scrolling https://cdn.discordapp.com/attachments/724248067145990148/747803029503344720/Screen_Shot_2020-08-25_at_9.01.55_AM.png ...

### ISSUE THREAD

**Issue by yukinno** [Quento-Solutions/Quento#215]
Can't see scroll bar scrolling https://cdn.discordapp.com/attachments/724248067145990148/747803029503344720/Screen_Shot_2020-08-25_at_9.01.55_AM.png

**Comment by DrCheddar** [comment]
fixed with #248
