### ISSUE TITLE
 https://cdn.discordapp.com/attachments/676598710003564596/752561473540194393/Screen_Recording_2020-09-07_at_12.09.37_PM.mov ...

### ISSUE THREAD

**Issue by yukinno** [Quento-Solutions/Quento#327]
-----REPORTED BY Burpcity#6395-----
 https://cdn.discordapp.com/attachments/676598710003564596/752561473540194393/Screen_Recording_2020-09-07_at_12.09.37_PM.mov

**Comment by Lucien950** [comment]
Basically, when you hover over the menu, it needs to stay open. It was designed that way. While it looks as though there is nothing left there its just becuase there is very low opacity, but its still there.
