### ISSUE TITLE
BUG: Reloading / Load More function disabled when unable to find notes in one subject, even when others are selected.

### ISSUE THREAD

**Issue by JavascriptIsTerrible** [Quento-Solutions/Quento#60]
When filtering for specific notes, sometimes the program is unable to retrieve any, whether due to networking issues or simply because of the lack of notes in that section. However, when this happens the reload button does not work, instead becoming greyed out and nonresponsive, even when other sections are selected. This necessitates a webpage reload.

**Comment by DrCheddar** [comment]
Clear the filter button and press filter - does that fix?

**Comment by JavascriptIsTerrible** [comment]
The button stays greyed-out still.
