### ISSUE TITLE
Restrict registration with email

### ISSUE THREAD

**Issue by angc7** [Quento-Solutions/Quento#72]
I wasn't aware that I was supposed to register with Google, so I registered my account with email, and ended up with a buggy profile with no name and no profile image :(
<img width="344" alt="Screen Shot 2020-08-16 at 9 14 00 PM" src="https://user-images.githubusercontent.com/65053157/90348848-69a37600-e005-11ea-9e77-a432c5fa7c91.png">
^ that's me

**Comment by JavascriptIsTerrible** [comment]
We are aware of this problem and are working on the registration system. In the meantime, please use Google to sign in and sign up.
